part of 'atem_fields.dart';

/// Parses a field from raw data.
AtemField parseAtemField(String code, Uint8List data) {
  switch (code) {
    case AtemFieldCode.programInput:
      return ProgramInputField(data);
    case AtemFieldCode.previewInput:
      return PreviewInputField(data);
    case AtemFieldCode.transitionPosition:
      return TransitionPositionField(data);
    case AtemFieldCode.transitionPreview:
      return TransitionPreviewField(data);
    case AtemFieldCode.transitionSettings:
      return TransitionSettingsField(data);
    case AtemFieldCode.keyOnAir:
      return KeyOnAirField(data);
    case AtemFieldCode.keyPropertiesBase:
      return KeyPropertiesBaseField(data);
    case AtemFieldCode.inputProperties:
      return InputPropertiesField(data);
    case AtemFieldCode.videoMode:
      return VideoModeField(data);
    case AtemFieldCode.productId:
      return ProductIdField(data);
    case AtemFieldCode.firmwareVersion:
      return FirmwareVersionField(data);
    case AtemFieldCode.topology:
      return TopologyField(data);
    case AtemFieldCode.mixerEffectConfig:
      return MixerEffectConfigField(data);
    case AtemFieldCode.multiviewerConfig:
      return MultiviewerConfigField(data);
    case AtemFieldCode.fairlightAudioConfig:
      return FairlightAudioConfigField(data);
    case AtemFieldCode.videoModeCapability:
      return VideoModeCapabilityField(data);
    case AtemFieldCode.macroConfig:
      return MacroConfigField(data);
    case AtemFieldCode.dveCapabilities:
      return DveCapabilitiesField(data);
    case AtemFieldCode.powerStatus:
      return PowerStatusField(data);
    case AtemFieldCode.mediaPlayerSlots:
      return MediaPlayerSlotsField(data);
    case AtemFieldCode.auxSource:
      return AuxSourceField(data);
    case AtemFieldCode.colorGenerator:
      return ColorGeneratorField(data);
    case AtemFieldCode.fadeToBlack:
      return FadeToBlackField(data);
    case AtemFieldCode.fadeToBlackState:
      return FadeToBlackStateField(data);
    case AtemFieldCode.dskPropertiesBase:
      return DskPropertiesBaseField(data);
    case AtemFieldCode.dskProperties:
      return DskPropertiesField(data);
    case AtemFieldCode.dskState:
      return DskStateField(data);
    case AtemFieldCode.autoInputVideoMode:
      return AutoInputVideoModeField(data);
    case AtemFieldCode.initComplete:
      return InitCompleteField(data);
    case AtemFieldCode.cameraControlData:
      return CameraControlDataField(data);
    case AtemFieldCode.multiviewerProperties:
      return MultiviewerPropertiesField(data);
    case AtemFieldCode.multiviewerInput:
      return MultiviewerInputField(data);
    case AtemFieldCode.supersourceProperties:
      return SuperSourcePropertiesField(data);
    case AtemFieldCode.supersourceBoxProperties:
      return SuperSourceBoxPropertiesField(data);
    case AtemFieldCode.macroProperties:
      return MacroPropertiesField(data);
    case AtemFieldCode.macroRecordStatus:
      return MacroRecordStatusField(data);
    case AtemFieldCode.macroPlayStatus:
      return MacroPlayStatusField(data);
    case AtemFieldCode.recordingDuration:
      return RecordingDurationField(data);
    case AtemFieldCode.recordingDisk:
      return RecordingDiskField(data);
    case AtemFieldCode.recordingStatus:
      return RecordingStatusField(data);
    case AtemFieldCode.recordingSettings:
      return RecordingSettingsField(data);
    case AtemFieldCode.streamingService:
      return StreamingServiceField(data);
    case AtemFieldCode.streamingAudioBitrate:
      return StreamingAudioBitrateField(data);
    case AtemFieldCode.usbAudioFunction:
      return UsbAudioFunctionField(data);
    case AtemFieldCode.streamingStatus:
      return StreamingStatusField(data);
    case AtemFieldCode.streamingStats:
      return StreamingStatsField(data);
    case AtemFieldCode.mediaplayerFileInfo:
      return MediaPlayerFileInfoField(data);
    case AtemFieldCode.mediaplayerSelected:
      return MediaPlayerSelectedField(data);
    case AtemFieldCode.mediaplayerClipSource:
      return MediaPlayerClipSourceField(data);
    case AtemFieldCode.mediaplayerAudioSource:
      return MediaPlayerAudioSourceField(data);
    case AtemFieldCode.mediaplayerClipStatus:
      return MediaPlayerClipStatusField(data);
    default:
      return UnknownField(code, data);
  }
}
