name: blackmagicdesign
description: Let's you develop your own remote application for BMD devices.
version: 1.0.0
homepage: https://github.com/SamsonChris71/blackmagicdesign

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0

dev_dependencies:
  dart_code_metrics: ^4.16.0
  lints: ^2.0.0
  test: ^1.16.0
