name: blackmagicdesign
description: Let's you develop your own remote application for BMD devices.
version: 0.0.2
homepage: https://github.com/SamsonChris71/blackmagicdesign

environment:
  sdk: ">=2.17.0 <3.0.0"
